// automatically generated by the FlatBuffers compiler, do not modify

package mindspore.schema;

public final class AggregationType {
  private AggregationType() { }
  public static final byte FedAvg = 0;
  public static final byte FedAdam = 1;
  public static final byte FedAdagrag = 2;
  public static final byte FedMeta = 3;
  public static final byte qffl = 4;

  public static final String[] names = { "FedAvg", "FedAdam", "FedAdagrag", "FedMeta", "qffl", };

  public static String name(int e) { return names[e]; }
}

