// automatically generated by the FlatBuffers compiler, do not modify

package mindspore.schema;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class EarlyStop extends Table {
  public static EarlyStop getRootAsEarlyStop(ByteBuffer _bb) { return getRootAsEarlyStop(_bb, new EarlyStop()); }
  public static EarlyStop getRootAsEarlyStop(ByteBuffer _bb, EarlyStop obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public EarlyStop __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte earlyStopType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public float weight() { int o = __offset(6); return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f; }
  public int rounds() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createEarlyStop(FlatBufferBuilder builder,
      byte early_stop_type,
      float weight,
      int rounds) {
    builder.startObject(3);
    EarlyStop.addRounds(builder, rounds);
    EarlyStop.addWeight(builder, weight);
    EarlyStop.addEarlyStopType(builder, early_stop_type);
    return EarlyStop.endEarlyStop(builder);
  }

  public static void startEarlyStop(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addEarlyStopType(FlatBufferBuilder builder, byte earlyStopType) { builder.addByte(0, earlyStopType, 0); }
  public static void addWeight(FlatBufferBuilder builder, float weight) { builder.addFloat(1, weight, 0.0f); }
  public static void addRounds(FlatBufferBuilder builder, int rounds) { builder.addInt(2, rounds, 0); }
  public static int endEarlyStop(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

