// automatically generated by the FlatBuffers compiler, do not modify

package mindspore.schema;

public final class EarlyStopType {
  private EarlyStopType() { }
  public static final byte loss_diff = 0;
  public static final byte loss_abs = 1;
  public static final byte weight_diff = 2;

  public static final String[] names = { "loss_diff", "loss_abs", "weight_diff", };

  public static String name(int e) { return names[e]; }
}

