// automatically generated by the FlatBuffers compiler, do not modify

package mindspore.schema;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FeatureMap extends Table {
  public static FeatureMap getRootAsFeatureMap(ByteBuffer _bb) { return getRootAsFeatureMap(_bb, new FeatureMap()); }
  public static FeatureMap getRootAsFeatureMap(ByteBuffer _bb, FeatureMap obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public FeatureMap __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String weightFullname() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer weightFullnameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer weightFullnameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public float data(int j) { int o = __offset(6); return o != 0 ? bb.getFloat(__vector(o) + j * 4) : 0; }
  public int dataLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer dataAsByteBuffer() { return __vector_as_bytebuffer(6, 4); }
  public ByteBuffer dataInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 4); }

  public static int createFeatureMap(FlatBufferBuilder builder,
      int weight_fullnameOffset,
      int dataOffset) {
    builder.startObject(2);
    FeatureMap.addData(builder, dataOffset);
    FeatureMap.addWeightFullname(builder, weight_fullnameOffset);
    return FeatureMap.endFeatureMap(builder);
  }

  public static void startFeatureMap(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addWeightFullname(FlatBufferBuilder builder, int weightFullnameOffset) { builder.addOffset(0, weightFullnameOffset, 0); }
  public static void addData(FlatBufferBuilder builder, int dataOffset) { builder.addOffset(1, dataOffset, 0); }
  public static int createDataVector(FlatBufferBuilder builder, float[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addFloat(data[i]); return builder.endVector(); }
  public static void startDataVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endFeatureMap(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

