// automatically generated by the FlatBuffers compiler, do not modify

package mindspore.schema;

public final class Metrics {
  private Metrics() { }
  public static final byte accuracy = 0;
  public static final byte precision = 1;
  public static final byte recall = 2;
  public static final byte AUC = 3;
  public static final byte f1 = 4;
  public static final byte fbeta = 5;

  public static final String[] names = { "accuracy", "precision", "recall", "AUC", "f1", "fbeta", };

  public static String name(int e) { return names[e]; }
}

