// automatically generated by the FlatBuffers compiler, do not modify

package mindspore.schema;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ResponseFLJob extends Table {
  public static ResponseFLJob getRootAsResponseFLJob(ByteBuffer _bb) { return getRootAsResponseFLJob(_bb, new ResponseFLJob()); }
  public static ResponseFLJob getRootAsResponseFLJob(ByteBuffer _bb, ResponseFLJob obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public ResponseFLJob __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int retcode() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String reason() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer reasonAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer reasonInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public int iteration() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public boolean isSelected() { int o = __offset(10); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public String nextReqTime() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nextReqTimeAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer nextReqTimeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }
  public FLPlan flPlanConfig() { return flPlanConfig(new FLPlan()); }
  public FLPlan flPlanConfig(FLPlan obj) { int o = __offset(14); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public FeatureMap featureMap(int j) { return featureMap(new FeatureMap(), j); }
  public FeatureMap featureMap(FeatureMap obj, int j) { int o = __offset(16); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int featureMapLength() { int o = __offset(16); return o != 0 ? __vector_len(o) : 0; }
  public String timestamp() { int o = __offset(18); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer timestampAsByteBuffer() { return __vector_as_bytebuffer(18, 1); }
  public ByteBuffer timestampInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 18, 1); }

  public static int createResponseFLJob(FlatBufferBuilder builder,
      int retcode,
      int reasonOffset,
      int iteration,
      boolean is_selected,
      int next_req_timeOffset,
      int fl_plan_configOffset,
      int feature_mapOffset,
      int timestampOffset) {
    builder.startObject(8);
    ResponseFLJob.addTimestamp(builder, timestampOffset);
    ResponseFLJob.addFeatureMap(builder, feature_mapOffset);
    ResponseFLJob.addFlPlanConfig(builder, fl_plan_configOffset);
    ResponseFLJob.addNextReqTime(builder, next_req_timeOffset);
    ResponseFLJob.addIteration(builder, iteration);
    ResponseFLJob.addReason(builder, reasonOffset);
    ResponseFLJob.addRetcode(builder, retcode);
    ResponseFLJob.addIsSelected(builder, is_selected);
    return ResponseFLJob.endResponseFLJob(builder);
  }

  public static void startResponseFLJob(FlatBufferBuilder builder) { builder.startObject(8); }
  public static void addRetcode(FlatBufferBuilder builder, int retcode) { builder.addInt(0, retcode, 0); }
  public static void addReason(FlatBufferBuilder builder, int reasonOffset) { builder.addOffset(1, reasonOffset, 0); }
  public static void addIteration(FlatBufferBuilder builder, int iteration) { builder.addInt(2, iteration, 0); }
  public static void addIsSelected(FlatBufferBuilder builder, boolean isSelected) { builder.addBoolean(3, isSelected, false); }
  public static void addNextReqTime(FlatBufferBuilder builder, int nextReqTimeOffset) { builder.addOffset(4, nextReqTimeOffset, 0); }
  public static void addFlPlanConfig(FlatBufferBuilder builder, int flPlanConfigOffset) { builder.addOffset(5, flPlanConfigOffset, 0); }
  public static void addFeatureMap(FlatBufferBuilder builder, int featureMapOffset) { builder.addOffset(6, featureMapOffset, 0); }
  public static int createFeatureMapVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startFeatureMapVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addTimestamp(FlatBufferBuilder builder, int timestampOffset) { builder.addOffset(7, timestampOffset, 0); }
  public static int endResponseFLJob(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

