// automatically generated by the FlatBuffers compiler, do not modify

package mindspore.schema;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ResponseUpdateAndCalMutualInformation extends Table {
  public static ResponseUpdateAndCalMutualInformation getRootAsResponseUpdateAndCalMutualInformation(ByteBuffer _bb) { return getRootAsResponseUpdateAndCalMutualInformation(_bb, new ResponseUpdateAndCalMutualInformation()); }
  public static ResponseUpdateAndCalMutualInformation getRootAsResponseUpdateAndCalMutualInformation(ByteBuffer _bb, ResponseUpdateAndCalMutualInformation obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public ResponseUpdateAndCalMutualInformation __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int retcode() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String reason() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer reasonAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer reasonInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String nextReqTime() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nextReqTimeAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer nextReqTimeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public String timestamp() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer timestampAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer timestampInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }

  public static int createResponseUpdateAndCalMutualInformation(FlatBufferBuilder builder,
      int retcode,
      int reasonOffset,
      int next_req_timeOffset,
      int timestampOffset) {
    builder.startObject(4);
    ResponseUpdateAndCalMutualInformation.addTimestamp(builder, timestampOffset);
    ResponseUpdateAndCalMutualInformation.addNextReqTime(builder, next_req_timeOffset);
    ResponseUpdateAndCalMutualInformation.addReason(builder, reasonOffset);
    ResponseUpdateAndCalMutualInformation.addRetcode(builder, retcode);
    return ResponseUpdateAndCalMutualInformation.endResponseUpdateAndCalMutualInformation(builder);
  }

  public static void startResponseUpdateAndCalMutualInformation(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addRetcode(FlatBufferBuilder builder, int retcode) { builder.addInt(0, retcode, 0); }
  public static void addReason(FlatBufferBuilder builder, int reasonOffset) { builder.addOffset(1, reasonOffset, 0); }
  public static void addNextReqTime(FlatBufferBuilder builder, int nextReqTimeOffset) { builder.addOffset(2, nextReqTimeOffset, 0); }
  public static void addTimestamp(FlatBufferBuilder builder, int timestampOffset) { builder.addOffset(3, timestampOffset, 0); }
  public static int endResponseUpdateAndCalMutualInformation(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

