// automatically generated by the FlatBuffers compiler, do not modify

package mindspore.schema;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ResponsePushMetrics extends Table {
  public static ResponsePushMetrics getRootAsResponsePushMetrics(ByteBuffer _bb) { return getRootAsResponsePushMetrics(_bb, new ResponsePushMetrics()); }
  public static ResponsePushMetrics getRootAsResponsePushMetrics(ByteBuffer _bb, ResponsePushMetrics obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public ResponsePushMetrics __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int retcode() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createResponsePushMetrics(FlatBufferBuilder builder,
      int retcode) {
    builder.startObject(1);
    ResponsePushMetrics.addRetcode(builder, retcode);
    return ResponsePushMetrics.endResponsePushMetrics(builder);
  }

  public static void startResponsePushMetrics(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addRetcode(FlatBufferBuilder builder, int retcode) { builder.addInt(0, retcode, 0); }
  public static int endResponsePushMetrics(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

