// automatically generated by the FlatBuffers compiler, do not modify

package mindspore.schema;

public final class ResponseCode {
  private ResponseCode() { }
  public static final int SUCCEED = 200;
  public static final int SucNotReady = 201;
  public static final int RepeatRequest = 202;
  public static final int SucNotMatch = 204;
  public static final int OutOfTime = 300;
  public static final int NotSelected = 301;
  public static final int RequestError = 400;
  public static final int SystemError = 500;
}

