// automatically generated by the FlatBuffers compiler, do not modify

package mindspore.schema;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ReturnClientList extends Table {
  public static ReturnClientList getRootAsReturnClientList(ByteBuffer _bb) { return getRootAsReturnClientList(_bb, new ReturnClientList()); }
  public static ReturnClientList getRootAsReturnClientList(ByteBuffer _bb, ReturnClientList obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public ReturnClientList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int retcode() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String reason() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer reasonAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer reasonInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String clients(int j) { int o = __offset(8); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int clientsLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public int iteration() { int o = __offset(10); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String nextReqTime() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nextReqTimeAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer nextReqTimeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }

  public static int createReturnClientList(FlatBufferBuilder builder,
      int retcode,
      int reasonOffset,
      int clientsOffset,
      int iteration,
      int next_req_timeOffset) {
    builder.startObject(5);
    ReturnClientList.addNextReqTime(builder, next_req_timeOffset);
    ReturnClientList.addIteration(builder, iteration);
    ReturnClientList.addClients(builder, clientsOffset);
    ReturnClientList.addReason(builder, reasonOffset);
    ReturnClientList.addRetcode(builder, retcode);
    return ReturnClientList.endReturnClientList(builder);
  }

  public static void startReturnClientList(FlatBufferBuilder builder) { builder.startObject(5); }
  public static void addRetcode(FlatBufferBuilder builder, int retcode) { builder.addInt(0, retcode, 0); }
  public static void addReason(FlatBufferBuilder builder, int reasonOffset) { builder.addOffset(1, reasonOffset, 0); }
  public static void addClients(FlatBufferBuilder builder, int clientsOffset) { builder.addOffset(2, clientsOffset, 0); }
  public static int createClientsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startClientsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addIteration(FlatBufferBuilder builder, int iteration) { builder.addInt(3, iteration, 0); }
  public static void addNextReqTime(FlatBufferBuilder builder, int nextReqTimeOffset) { builder.addOffset(4, nextReqTimeOffset, 0); }
  public static int endReturnClientList(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

