// automatically generated by the FlatBuffers compiler, do not modify

package mindspore.schema;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ReturnExchangeKeys extends Table {
  public static ReturnExchangeKeys getRootAsReturnExchangeKeys(ByteBuffer _bb) { return getRootAsReturnExchangeKeys(_bb, new ReturnExchangeKeys()); }
  public static ReturnExchangeKeys getRootAsReturnExchangeKeys(ByteBuffer _bb, ReturnExchangeKeys obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public ReturnExchangeKeys __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int retcode() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int iteration() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public ClientPublicKeys remotePublickeys(int j) { return remotePublickeys(new ClientPublicKeys(), j); }
  public ClientPublicKeys remotePublickeys(ClientPublicKeys obj, int j) { int o = __offset(8); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int remotePublickeysLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public String nextReqTime() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nextReqTimeAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }
  public ByteBuffer nextReqTimeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 10, 1); }

  public static int createReturnExchangeKeys(FlatBufferBuilder builder,
      int retcode,
      int iteration,
      int remote_publickeysOffset,
      int next_req_timeOffset) {
    builder.startObject(4);
    ReturnExchangeKeys.addNextReqTime(builder, next_req_timeOffset);
    ReturnExchangeKeys.addRemotePublickeys(builder, remote_publickeysOffset);
    ReturnExchangeKeys.addIteration(builder, iteration);
    ReturnExchangeKeys.addRetcode(builder, retcode);
    return ReturnExchangeKeys.endReturnExchangeKeys(builder);
  }

  public static void startReturnExchangeKeys(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addRetcode(FlatBufferBuilder builder, int retcode) { builder.addInt(0, retcode, 0); }
  public static void addIteration(FlatBufferBuilder builder, int iteration) { builder.addInt(1, iteration, 0); }
  public static void addRemotePublickeys(FlatBufferBuilder builder, int remotePublickeysOffset) { builder.addOffset(2, remotePublickeysOffset, 0); }
  public static int createRemotePublickeysVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRemotePublickeysVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addNextReqTime(FlatBufferBuilder builder, int nextReqTimeOffset) { builder.addOffset(3, nextReqTimeOffset, 0); }
  public static int endReturnExchangeKeys(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

